name: Python script run

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run script
      run: python backend/api.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        XI_API_KEY: ${{ secrets.XI_API_KEY }}
